import { Schema, model } from 'mongoose';
import { Vendor } from '../../../packages/shared-types';

const vendorPackageSchema = new Schema(
  {
    id: String,
    packageName: String,
    price: Number,
    pricePerPlate: Number,
    description: String,
    includedServices: [String],
    durationHours: Number,
    capacityPersons: Number,
    images: [String],
    tiers: [{ name: String, price: Number, _id: false }],
    // Catering-only structured menu details.
    catering: {
      type: {
        menuTier: String,
        pricePerPlate: Number,
        foodTypes: [String],
        foodTypeItems: { type: Schema.Types.Mixed, default: {} },
        foodTypeImages: { type: Schema.Types.Mixed, default: {} },
        cuisines: [String],
        cuisineItems: { type: Schema.Types.Mixed, default: {} },
        cuisineImages: { type: Schema.Types.Mixed, default: {} },
        courses: [String],
        courseItems: { type: Schema.Types.Mixed, default: {} },
        starters: Number,
        mains: Number,
        desserts: Number,
        minGuests: Number,
        liveCounters: [String],
        liveCounterItems: { type: Schema.Types.Mixed, default: {} },
        serviceStyle: String,
        plateTypes: [String],
        leafType: String,
        welcomeDrinks: Boolean,
        welcomeDrinkItems: [{ name: String, price: Number, _id: false }],
        servingStaff: Boolean,
        freeTasting: Boolean,
        freeTastingItems: [String],
      },
      default: undefined,
      _id: false,
    },
    // Venue-only structured hall details.
    venue: {
      type: {
        sessions: [String],
        hallType: String,
        hallTypePrice: Number,
        hallClass: String,
        hallClassPrice: Number,
        parking: Boolean,
        powerBackup: Boolean,
        bridalRoom: Boolean,
        accommodationRooms: Number,
        cateringPolicy: String,
        cateringPrice: Number,
        cateringImage: String,
        stageIncluded: Boolean,
        valetService: Boolean,
        featurePrices: Schema.Types.Mixed,
        featureImages: Schema.Types.Mixed,
      },
      default: undefined,
      _id: false,
    },
    // Decoration-only structured details.
    decoration: {
      type: {
        tier: String,
        themes: [String],
        themePrices: Schema.Types.Mixed,
        themeImages: Schema.Types.Mixed,
        areas: [String],
        areaPrices: Schema.Types.Mixed,
        areaImages: Schema.Types.Mixed,
        flowers: String,
        flowerPrices: Schema.Types.Mixed,
        flowerImages: Schema.Types.Mixed,
        coupleSofa: Boolean,
        mandapType: String,
        mandapPrice: Number,
        mandapImage: String,
        lighting: Boolean,
        functionsCovered: Number,
      },
      default: undefined,
      _id: false,
    },
    // Makeup & Beauty-only structured details.
    makeup: {
      type: {
        makeupTypes: [String],
        makeupTypePrices: Schema.Types.Mixed,
        makeupTypeImages: Schema.Types.Mixed,
        finish: String,
        finishPrice: Number,
        hairstyleName: String,
        hairstylePrice: Number,
        hairstyling: Boolean,
        draping: Boolean,
        drapingPrice: Number,
        looksCount: Number,
        trialSession: Boolean,
        travelToVenue: Boolean,
        travelPrice: Number,
        extraFamilyMembers: Number,
        extraFamilyPrice: Number,
      },
      default: undefined,
      _id: false,
    },
    // Media (Photo/Video)-only structured details.
    media: {
      type: {
        tier: String,
        coverage: String,
        coveragePrice: Number,
        coverageImage: String,
        coverageSize: String,
        coverageQuality: String,
        styles: [String],
        stylePrices: Schema.Types.Mixed,
        styleImages: Schema.Types.Mixed,
        daysOrEvents: Number,
        daysPrice: Number,
        preWedding: Boolean,
        drone: Boolean,
        crewCount: Number,
        crewPrice: Number,
        editedPhotos: Number,
        albumType: String,
        albumTypePrice: Number,
        photoFrameSize: String,
        photoFramePrice: Number,
        albumPages: Number,
        albumPagesPrice: Number,
        teaser: Boolean,
        film4k: Boolean,
        hoursCoverage: Number,
        hoursPrice: Number,
        featurePrices: Schema.Types.Mixed,
        featureQuality: Schema.Types.Mixed,
        featureImages: Schema.Types.Mixed,
      },
      default: undefined,
      _id: false,
    },
    // Transport-only structured details.
    transport: {
      type: {
        tier: String,
        vehicleType: String,
        vehicleTypes: [String],
        vehicleTypeSeats: { type: Schema.Types.Mixed, default: {} },
        vehicleTypePrices: { type: Schema.Types.Mixed, default: {} },
        vehicleTypeImages: { type: Schema.Types.Mixed, default: {} },
        pricingBasis: String,
        perDayPrice: Number,
        perKmPrice: Number,
        numVehicles: Number,
        numVehiclesPrice: Number,
        seatsPerVehicle: Number,
        seatsPrice: Number,
        kmHoursIncluded: Number,
        kmHoursPrice: Number,
        driverFuel: Boolean,
        driverFuelPrice: Number,
        carDecoration: Boolean,
        carDecorationType: String,
        carDecorationPrice: Number,
        carDecorationImage: String,
        use: String,
        uses: [String],
        usePrices: { type: Schema.Types.Mixed, default: {} },
        baraatHours: Number,
        guestsPersons: Number,
      },
      default: undefined,
      _id: false,
    },
    // Pujari/Priest-only structured details.
    priest: {
      type: {
        ceremonyType: String,
        community: String,
        languages: [String],
        samagriIncluded: Boolean,
        numPriests: Number,
        durationHours: Number,
        muhurthamConsult: Boolean,
      },
      default: undefined,
      _id: false,
    },
    // Invitation-only structured details.
    // Plain nested object (not the `type:` wrapper) because it has a field
    // literally named "type", which the wrapper form misreads as a Mongoose
    // type declaration. `type: { type: String }` is the correct way to declare
    // a String field named "type".
    invitation: {
      tier: String,
      type: { type: String },
      types: [String],
      typePrices: { type: Schema.Types.Mixed, default: {} },
      typeImages: { type: Schema.Types.Mixed, default: {} },
      design: String,
      designPrices: { type: Schema.Types.Mixed, default: {} },
      quantity: Number,
      quantityPrice: Number,
      revisions: Number,
      addOns: [String],
      addOnPrices: { type: Schema.Types.Mixed, default: {} },
      deliveryTime: String,
      languages: [String],
      languagePrice: Number,
    },
    // Printing-only structured details.
    printing: {
      product: String,
      products: [String],
      productTypes: { type: Schema.Types.Mixed, default: {} },
      productSizes: { type: Schema.Types.Mixed, default: {} },
      productPrices: { type: Schema.Types.Mixed, default: {} },
      productImages: { type: Schema.Types.Mixed, default: {} },
      size: String,
      quantity: Number,
      finishes: [String],
      finishPrices: { type: Schema.Types.Mixed, default: {} },
      finishImages: { type: Schema.Types.Mixed, default: {} },
      designIncluded: Boolean,
      designPrice: Number,
      designDescription: String,
      designImage: String,
      deliveryTime: String,
    },
    // Return Gifts-only structured details.
    returnGifts: {
      tier: String,
      giftType: String,
      giftTypes: [String],
      giftItemDetails: { type: Schema.Types.Mixed, default: {} },
      giftPrices: { type: Schema.Types.Mixed, default: {} },
      giftImages: { type: Schema.Types.Mixed, default: {} },
      countOfGifts: Number,
      countPrice: Number,
      packagingType: String,
      packagingPrice: Number,
      customization: Boolean,
      customizationPrice: Number,
      customerCustomizationText: String,
      minQuantity: Number,
      packingTimeDays: Number,
      bulkDiscount: String,
    },
    // Entertainment-only structured details.
    entertainment: {
      actType: String,
      equipmentIncluded: Boolean,
      travelIncluded: Boolean,
      actTypes: [String],
      actTypePrices: Schema.Types.Mixed,
      actTypeImages: Schema.Types.Mixed,
      equipmentPrice: Number,
      travelPrice: Number,
    },
    // Music/DJ-only structured details. Plain nested (has a `type` field, which
    // must be declared as `type: { type: String }` — see invitation above).
    musicDj: {
      tier: String,
      type: { type: String },
      hours: Number,
      soundSystem: Boolean,
      lighting: Boolean,
      numArtists: Number,
      mcHost: Boolean,
      venueType: String,
      generator: Boolean,
    },
    // Lighting-only structured details.
    lighting: {
      tier: String,
      lightingTypes: [String],
      typePrices: { type: Map, of: Number },
      typeItems: { type: Map, of: String },
      typeImages: { type: Map, of: String },
      areaCovered: String,
      areaCoveredPrice: Number,
      numFixtures: Number,
      powerBackup: Boolean,
      powerBackupPrice: Number,
      setupTeardown: Boolean,
      setupTeardownPrice: Number,
      numFunctions: Number,
    },
    // Flowers-only structured details.
    flowers: {
      variety: String,
      varieties: [String],
      varietyPrices: Schema.Types.Mixed,
      varietyImages: Schema.Types.Mixed,
      customVarieties: [{
        name: String,
        price: Number,
        image: String,
      }],
      items: [String],
      itemPrices: Schema.Types.Mixed,
      itemImages: Schema.Types.Mixed,
      customItems: [{
        name: String,
        price: Number,
        image: String,
      }],
      flowerKind: String,
      flowerKindPrices: Schema.Types.Mixed,
      flowerKindImages: Schema.Types.Mixed,
      quantity: Number,
      unitPrice: Number,
      quantityPrice: Number,
      deliveryTiming: String,
      deliveryTimingPrice: Number,
      whichFunction: String,
      whichFunctionPrice: Number,
    },
    // Mehendi-only structured details. Plain nested (has a `type` field).
    mehendi: {
      tier: String,
      type: { type: String },
      intricacy: String,
      organicHenna: Boolean,
      travelIncluded: Boolean,
      perHandPrice: Number,
      durationHours: Number,
      tiers: [String],
      tierPrices: Schema.Types.Mixed,
      tierImages: Schema.Types.Mixed,
      intricacies: [String],
      intricacyPrices: Schema.Types.Mixed,
      intricacyImages: Schema.Types.Mixed,
      typePrices: Schema.Types.Mixed,
      numArtists: Number,
      artistsPrice: Number,
      organicHennaPrice: Number,
      travelPrice: Number,
    },
    // Event Host/Anchor-only structured details.
    eventHost: {
      eventType: String,
      languages: [String],
      hours: Number,
      numEvents: Number,
      gamesScripting: Boolean,
      hostMode: String,
      travelIncluded: Boolean,
    },
    // Security-only structured details. Plain nested (has a `type` field).
    security: {
      numGuards: Number,
      type: { type: String },
      gender: String,
      hoursShifts: Number,
      metalDetectors: Boolean,
      cctv: Boolean,
      vipProtection: Boolean,
      crowdManagement: Boolean,
      genders: [String],
      genderNames: Schema.Types.Mixed,
      genderPrices: Schema.Types.Mixed,
      genderImages: Schema.Types.Mixed,
      metalDetectorsPrice: Number,
      cctvPrice: Number,
      vipProtectionPrice: Number,
      crowdManagementPrice: Number,
    },
    // Rental Equipment-only structured details.
    rental: {
      items: [String],
      itemQuantities: Schema.Types.Mixed,
      itemPrices: Schema.Types.Mixed,
      itemDetails: Schema.Types.Mixed,
      itemImages: Schema.Types.Mixed,
      deliveryPrice: Number,
      quantity: Number,
      setupTeardown: Boolean,
      delivery: Boolean,
      securityDeposit: Number,
    },
    // Utensils for Rent-only structured details.
    utensils: {
      material: String,
      vesselTypes: [String],
      vesselTypePrices: Schema.Types.Mixed,
      basePrice: Number,
      guestCount: Number,
      deliveryPickup: Boolean,
      deliveryPickupPrice: Number,
      cleaningIncluded: Boolean,
      securityDeposit: Number,
    },
    // Wedding Planner-only structured details.
    weddingPlanner: {
      scope: String,
      numFunctions: Number,
      vendorCoordination: Boolean,
      budgetManagement: Boolean,
      teamSize: Number,
      guestManagement: Boolean,
      planningMeetings: Number,
    },
    // Corporate Event Services-only structured details. Each add-on carries its
    // own price (₹) so they're priced separately.
    corporate: {
      eventType: String,
      eventTypePrices: Schema.Types.Mixed,
      numAttendees: Number,
      numDays: Number,
      avStageBranding: Number,
      registrationDesk: Number,
      cateringCoordination: Number,
      mcHost: Number,
    },
  },
  { _id: false }
);

const vendorDealSchema = new Schema(
  {
    id: String,
    title: String,
    description: String,
    discountType: { type: String, enum: ['percent', 'flat'], default: 'percent' },
    discountValue: Number,
    minOrderAmount: Number,
    startsAt: String,
    expiresAt: String,
    isActive: { type: Boolean, default: true },
    createdAt: { type: String, default: () => new Date().toISOString() },
  },
  { _id: false }
);

const vendorSchema = new Schema<Vendor>({
  id: { type: String, required: true, unique: true },
  userId: { type: String, required: true },
  businessName: { type: String, required: true },
  category: { type: String, required: true },
  description: { type: String, default: '' },
  location: {
    type: { type: String, enum: ['Point'], default: 'Point' },
    coordinates: { type: [Number], default: [0, 0] },
    address: String,
    city: String,
    district: String,
    state: String,
    pincode: String,
  },
  startingPrice: { type: Number, default: 0 },
  yearsOfExperience: { type: Number, default: 0 },
  ratingAverage: { type: Number, default: 0 },
  reviewCount: { type: Number, default: 0 },
  isVerified: { type: Boolean, default: false },
  isSuspended: { type: Boolean, default: false },
  featured: { type: Boolean, default: false },
  galleryImages: { type: [String], default: [] },
  galleryVideos: { type: [String], default: [] },
  contactEmail: String,
  contactPhone: String,
  upiId: String,
  qrCodeImage: String,
  packages: { type: [vendorPackageSchema], default: [] },
  availableDates: { type: [String], default: [] },
  // Slots the vendor offers per date (map date -> [slot ids]). Empty = all slots.
  availableSlots: { type: Schema.Types.Mixed, default: {} },
  bookedDates: { type: [String], default: [] },
  // Per-date time slots already booked (e.g. { date, slot: 'morning' }).
  bookedSlots: { type: [{ date: String, slot: String, _id: false }], default: [] },
  policies: {
    cancellation: { type: String, default: '' },
    refund: { type: String, default: '' },
    advancePercentage: { type: Number, default: 20 },
    advanceAmount: { type: Number },
  },
  // Amenities / options a vendor offers — set in the vendor portal, shown on the
  // customer marketplace chips.
  facilities: {
    acRoom: Boolean,
    fansOnly: Boolean,
    vipRoom: Boolean,
    vipFrontChairs: Boolean,
    garlands: Boolean,
    brideGroomRoom: Boolean,
    guestRoomAttachedWashroom: Boolean,
    dormitoryHall: Boolean,
    separateGuestWashroom: Boolean,
    cookingUtensils: Boolean,
    waterFilter: Boolean,
    catering: String,
    decoration: String,
    djService: String,
    transport: String,
  },
  // Category-specific services this vendor offers (e.g. a caterer's menu sections,
  // a photographer's shoot styles) — shown on the customer vendor detail page.
  offeredOptions: { type: [String], default: [] },
  // Price the vendor set for each entry in offeredOptions, keyed by label.
  offeredOptionPrices: { type: Schema.Types.Mixed, default: {} },
  // Named priced line-items the vendor lists under each offered option, keyed
  // by label — e.g. { "Veg": [{ name, price, note }, ...] }.
  offeredOptionItems: { type: Schema.Types.Mixed, default: {} },
  // Option-level quality tier keyed by label, for options with no item list —
  // e.g. { "Live Streaming": "4K Ultra HD" }.
  offeredOptionQuality: { type: Schema.Types.Mixed, default: {} },
  // Photos per offered option, keyed by label — { "Fresh Flower Decor": [url] }.
  offeredOptionImages: { type: Schema.Types.Mixed, default: {} },
  giftCount: Number,
  giftDiscount: String,
  // Promotional deals the vendor publishes on their own listing.
  deals: { type: [vendorDealSchema], default: [] },
  // Verification request the vendor submits to earn the Verified badge; reviewed
  // by an admin. `isVerified` above mirrors verification.status === 'verified'.
  verification: {
    status: { type: String, enum: ['unverified', 'pending', 'verified', 'rejected'], default: 'unverified' },
    legalName: { type: String, default: '' },
    registrationNumber: { type: String, default: '' },
    gstNumber: { type: String, default: '' },
    contactPerson: { type: String, default: '' },
    documents: { type: [String], default: [] },
    submittedAt: { type: String, default: '' },
    reviewedAt: { type: String, default: '' },
    rejectionReason: { type: String, default: '' },
  },
  createdAt: { type: String, default: () => new Date().toISOString() },
});

vendorSchema.index({ location: '2dsphere' });
vendorSchema.index({ businessName: 'text', description: 'text' });
vendorSchema.index({ category: 1, 'location.city': 1 });

export const VendorModel = model<Vendor>('Vendor', vendorSchema);
